language: go
sudo: false
go:
  - 1.6.3
  - 1.7
  - 1.7.1
  - tip
install:
  - go get -u github.com/golang/lint/golint
script:
  - test -z "$(golint ./... | tee /dev/stderr)"
  - go test -v .
  - go test -v -bench . -benchmem
matrix:
  allow_failures:
    - go: tip
